//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ALIMENTACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALIMENTACION()
        {
            this.POTREROS = new HashSet<POTREROS>();
        }

        // [DisplayFormat(ApplyFormatInEditMode = true)] permite aplicar las validaciones definidas en las anotaciones en los campos de edición y creación

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Identificador de alimentación en el sistema")]
        public int ID_ALIMENTACION { get; set; }

        [DisplayName("Tipo de alimentación")]
        public string TIPO_ALIMENTACION { get; set; }

        [DisplayName("Propósito")]
        public string PROPOSITO { get; set; }

        [NotMapped]
        [DisplayName("Descripción")]
        public string DESCRIPCION_ALIMENTACION { get { return this.TIPO_ALIMENTACION + " " + this.PROPOSITO; } }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTREROS> POTREROS { get; set; }
    }
}
