//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int ID_ERROR { get; set; }
        public string DESCRIPCION_ERROR { get; set; }
        public System.DateTime FECHA_ERROR { get; set; }
    }
}
