//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class COLABORADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADORES()
        {
            this.VACUNAS = new HashSet<VACUNAS>();
        }

        // [DisplayFormat(ApplyFormatInEditMode = true)] permite aplicar las validaciones definidas en las anotaciones en los campos de edición y creación

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Identificador en el sistema")]
        public int ID_COLABORADOR { get; set; }
        
        //Concurrency check removido
        //[ConcurrencyCheck]
        [Required]
        [DisplayName("Documento de identidad")]
        public string IDENTIFICACION_LEGAL { get; set; }

        [DisplayName("Nombre")]
        public string NOMBRE { get; set; }

        [DisplayName("Apellidos")]
        public string APELLIDOS { get; set; }

        [NotMapped]
        [DisplayName("Nombre completo")]
        public string NOMBRE_COMPLETO { get { return this.NOMBRE + " " + this.APELLIDOS; } }


        [DisplayName("Identificador de usuario del sistema")]
        public int ID_USUARIO { get; set; }

        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACUNAS> VACUNAS { get; set; }
    }
}
