//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class POTREROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POTREROS()
        {
            this.RESES = new HashSet<RESES>();
        }

        // [DisplayFormat(ApplyFormatInEditMode = true)] permite aplicar las validaciones definidas en las anotaciones en los campos de edición y creación

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Identificador de potrero en el sistema")]
        public int ID_POTRERO { get; set; }

        [DisplayName("Señas del potrero")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string DESCRIPCION_POTRERO { get; set; }

        [DisplayName("Finca a la que pertenece")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public int ID_FINCA { get; set; }

        [DisplayName("ID de Alimentación disponible")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public int ID_ALIMENTACION { get; set; }

        public virtual ALIMENTACION ALIMENTACION { get; set; }
        public virtual FINCAS FINCAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESES> RESES { get; set; }
    }
}
