//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RESES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESES()
        {
            this.VACUNAS = new HashSet<VACUNAS>();
        }

        // [DisplayFormat(ApplyFormatInEditMode = true)] permite aplicar las validaciones definidas en las anotaciones en los campos de edición y creación

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Identificador de res en el sistema")]
        public int ID_RES { get; set; }

        [DisplayName("Raza")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string RAZA { get; set; }

        [DisplayName("Fierro")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string FIERRO { get; set; }

        [DisplayName("Sexo")]
        [RegularExpression("^(M|H)$")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string SEXO { get; set; }

        [DisplayName("Fecha de nacimiento aproximada")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA_NACIMIENTO_APROX { get; set; }

        // No existe un método .Months para un timespan.
        // Se hizo un aproximado, dado la alicación teórica de una edad en meses para una res no es afectada por diferencias de frecciones de día
        [NotMapped]
        [DisplayName("Edad aproximada en meses")]
        public string EDAD_MESES {
            get 
            { 
                return ((int)
                    (System.DateTime.Today.Subtract
                    (this.FECHA_NACIMIENTO_APROX).Days / (365.2425 / 12))
                    ).ToString(); 
            } 
        }

        [NotMapped]
        [DisplayName("Sexo")]
        public string SexoFull
        {
            get
            {
                string resultado = "Datos no definidos o erróneos";
                if (this.SEXO == "M" || this.SEXO == "m")
                {
                    resultado = "Macho";
                } 
                else 
                {
                    if (this.SEXO == "H" || this.SEXO == "h")
                    {
                        resultado = "Hembra";
                    }
                }

                return resultado;
            }
        }

        [DisplayName("Potrero en que se encuentra")]
        public int ID_POTRERO { get; set; }

        public virtual POTREROS POTREROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACUNAS> VACUNAS { get; set; }
    }
}
