//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_CONTROL.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.COLABORADORES = new HashSet<COLABORADORES>();
        }

        // [DisplayFormat(ApplyFormatInEditMode = true)] permite aplicar las validaciones definidas en las anotaciones en los campos de edición y creación

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Identificador de usuario en el sistema")]
        public int ID_USUARIO { get; set; }


        [Required]
        [DisplayName("Correo electrónico")]
        [StringLength(30, ErrorMessage = "El correo electrónico debe tener menos de 30 caracteres")]
        [EmailAddressAttribute(ErrorMessage = "Formato incorrecto")] //https://stackoverflow.com/questions/25994423/emailaddress-or-datatype-email-attribute
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string EMAIL { get; set; }

        [DisplayName("Rol")]
        [RegularExpression("^(Campo|Administrativo)$", ErrorMessage = "El rol del usuario debe ser Administrativo o Campo" )]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string ROL { get; set; }

        [Required]
        [PasswordPropertyText]
        [DisplayName("Contraseña")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "La contraseña debe tener entre 5 y 30 caracteres")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string PASSWORD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADORES> COLABORADORES { get; set; }
    }
}
